{% set name = "textstat" %}
{% set version = "0.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 60b63cf8949f45bbb3b4205e4411bbc1cd66df4c08aef12545811c7e6e24f011

build:
  number: 0
  skip: True  # [py<36]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - pyphen
    - python

test:
  imports:
    - textstat
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/shivam5992/textstat
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Calculate statistical features from text
  description: |
    Textstat is an easy to use library to calculate statistics from text. It helps determine readability, complexity, and grade level.
  doc_url: https://github.com/textstat/textstat
  dev_url: https://github.com/shivam5992/textstat

extra:
  recipe-maintainers:
    - mxr-conda
    - mwilson8
    - oblute
    - benhuff
